### ISSUE TITLE
`On-chain Submit` button not functioning

### ISSUE THREAD

**Issue by RCantu92** [Keyrxng/GhostsOfEpochsPast#1]
Trying to submit responses onchain never leads to a Metamask prompt. Other buttons seemed to work (like minting a warm NFT for Race 4), but not the submission button. At least for Race 4.
Neither does `Mint Warm Up NFT for race 1!`, but I don't know whether I'd need to successfully submit race 4.

Also, when I say "race 4", I mean the first one. I see at some parts it's referred to as "race 0" and elsewhere as "race 4".

**Comment by Keyrxng** [comment]
I had no idea this was actually being used, and it sounds like it's still the first version too and not the most recent build...

Appreciate you taking the time tho, let me ship the newer build later today and get back to you

**Comment by Keyrxng** [comment]
> Also, when I say "race 4", I mean the first one. I see at some parts it's referred to as "race 0" and elsewhere as "race 4".

The Secureum races were released from number 4 onwards so it's confusing either way I've been told

Thanks opening the issue, gave me the kick up the ass I needed to put a bit of time into it.

Over time I'll add more features and cover more races etc if either are requested down the line.

Happy hunting.
